// <auto-generated />
namespace RestoReservationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Updateforadmin_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateforadmin_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202501312048121_Update-for-admin_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
