// <auto-generated />
namespace RestoReservationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class reservation_phone_field_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reservation_phone_field_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202502072104435_reservation_phone_field_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
